name: API Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    # Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Verificar estructura del proyecto
    - name: Ensure pom.xml exists
      run: |
        if [ ! -f pom.xml ]; then
          echo "Error: pom.xml no encontrado en el directorio raíz." >&2
          exit 1
        fi

    # Instalar dependencias y ejecutar pruebas
    - name: Build and Test with Maven
      run: |
        mvn clean install

     
