name: API Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    # Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Cambia si necesitas Java 8 o superior
        distribution: 'temurin'

    # Configurar Maven
    - name: Setup Maven
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    # Instalar dependencias con Maven
    - name: Install dependencies
      run: mvn clean install

    # Ejecutar pruebas
    - name: Run API Tests
      run: mvn test

